name: Java Maven CI
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
  IMAGE_NAME: baneymelo/order-app

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Fetch all history for all branches and tags

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'

            - name: Build JAR
              run: ./build.sh

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build & Push Docker image
              run: |
                IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7) 
                echo "IMAGE_DOCKER=$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV
                echo 'Image: ' $IMAGE_DOCKER
                docker build -t $IMAGE_DOCKER .
                docker push $IMAGE_DOCKER

            - name: Set up IMAGE_DOCKER environment variable
              run: |
                
                IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)
                IMAGE_DOCKER=$IMAGE_NAME:$IMAGE_TAG
                
                echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
                echo "IMAGE_DOCKER=$IMAGE_DOCKER" >> $GITHUB_ENV

            - name: Build & Push Docker image
              run: ./ci-scripts/build-and-push.sh

            - name: Checkout order-service-gitops repo
              uses: actions/checkout@v4
              with:
                repository: baneymelo/order-service-gitops
                token: ${{ secrets.GITOPS_TOKEN }}
                path: gitops

            - name: Updating k8s manifest
              run: |
                cd gitops
                echo "Updating image to ${IMAGE_DOCKER}" 
                sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_DOCKER|" deployment.yaml

            - name: Commit and push changes to GitOps repo
              run: |
               cd gitops
               git config user.name "GitHub Actions"
               git config user.email "actions@github.com"
               git add .
               git commit -m "Update image to $IMAGE_DOCKER"
               git push


    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Fetch all history for all branches and tags
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'

            - name: Run tests with Maven
              run: ./test.sh